# Generated by Django 5.2.1 on 2025-06-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='avatar',
            field=models.CharField(blank=True, default='public/images/User.svg', help_text='Caminho para o arquivo de avatar do usuário.', max_length=255, null=True),
        ),
    ]
