# Generated by Django 5.2.1 on 2025-06-07 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['coluna__ordem', '-data_criacao', 'titulo'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='tags',
        ),
        migrations.CreateModel(
            name='Coluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='public.projeto')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='coluna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='public.coluna'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tarefas', to='public.tag'),
        ),
    ]
