# Generated by Django 5.2.1 on 2025-06-09 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_tarefa_options_remove_tarefa_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='iteration_duration',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='projeto',
            name='iteration_unit',
            field=models.CharField(default='weeks', max_length=10),
        ),
        migrations.AddField(
            model_name='sprint',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='public.projeto'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='NAO_INICIADO', max_length=20),
        ),
    ]
