# Generated by Django 5.2.1 on 2025-06-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_usuariopersonalizado_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='nota',
            field=models.FloatField(blank=True, help_text='Nota atribuída ao milestone, de 0 a 10.', null=True),
        ),
    ]
