# Generated by Django 5.2.1 on 2025-06-09 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_projeto_iteration_duration_projeto_iteration_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='status',
        ),
        migrations.AlterField(
            model_name='sprint',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='public.projeto'),
        ),
    ]
