# Generated by Django 5.2.1 on 2025-06-25 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_milestone_feedback_projeto_feedback_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='visivel_para',
            field=models.ForeignKey(blank=True, help_text='Se a visibilidade for específica, este é o único usuário que pode ver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_visiveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status_update_text',
            field=models.TextField(blank=True, help_text='Texto da última atualização de status do projeto.', null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('PLANEJAMENTO', 'Em Planejamento'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('SUSPENSO', 'Suspenso')], default='PLANEJAMENTO', max_length=20),
        ),
    ]
