# Generated by Django 5.2.1 on 2025-06-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_remove_sprint_status_alter_sprint_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Fechado')], default='OPEN', max_length=10),
        ),
    ]
