name: ✅ Autorização Manual de Merge

on:
  workflow_dispatch:
    inputs:
      justificativa:
        description: "Justificativa para liberação manual do merge"
        required: true
        type: string

jobs:
  autorizacao-manual:
    runs-on: ubuntu-latest
    environment:
      name: merge-approval # Ambiente restrito a você
    steps:
      - name: ✅ Aprovação simbólica registrada
        run: |
          echo "Merge autorizado manualmente por ${{ github.actor }}"
          echo "Justificativa: ${{ inputs.justificativa }}"
